const randuser = '${randuser}'
module.exports = [
  // Hier die positiven Antworten
  'Ja',
  'Jawohl',
  'Freilich',
  'Ich stimme zu',
  'Okeh',
  'Sajebis kaneschno',
  'Jo Freili',
  'Ja, ich halte das für eine gute Idee',
  'Ja des is so!',
  'Hihihi si.',
  'Yay.',
  'Hat die Antwort beim Teeblätter-Lesen gefunden und stimmt zu.',
  '/jafrosch',
  '/jaja',
  'Ja, denn es dient dem Führer /adizf',
  'Ja. Und jetzt raus hier, aber schnell!',
  'כן',
  'Ja sischer dat.',
  'Klare Kante: Ja!',
  'Na klar.',
  'Ausnahmsweise bewilligt.',
  'Aber natürlich Bernd, immer doch.',
  'Hm, ich überlege noch... /2überlege ... Ja.',
  'Ja zur AfD und deiner Frage!',
  'Bekenne dich für unschuldig und die Antwort auf deine Frage soll positiv sein.',
  'Nö, ja, nö, nein, nö, jep, ne, jo, ji, ja... Ja!',
  'ist sich da sicher',
  'Natürlich',
  'Selbstverständlich',
  'Gewiss',
  'Freilich',
  'Diesmal Ja',
  `Ich habe dies mit ${randuser} besprochen und stimme zu /:3`,
  'Einverstanden',
  'JA!, fürs Vaterland /heilchen',
  'Ich unterstütze dich bei deinem Vorhaben',
  'Wenn es denn sein muss',
  '11/10 Klar doch Bernd. /nice',
  'Meinetwegen',
  'Na glar XDXDXDXD /spurdo',
  'Ja, du gönnst dir doch sonst nichts /patpat',
  'Auf jeden Brudi /fingerchen',
  'Warum eigentlich nicht /glad',
  'Sicher, du hast doch ohnehin schon die Kontrolle über dein Leben verloren',
  'Kühle Idee Bernd /top',
  'Der Zentralrat der Juden hat entschieden: JA',
  'Nach komplexen statistischen Berechnungen, bin ich glücklich, dir ein JA als Anwort zu geben /glad',
  'Ja, wünsche dir viel Spass dabei',
  'Ja, weil du so ein Lieber bist /:3',
  `${randuser} hat mich gezwungen dir ein Ja als Antwort zu geben /schwitz`,
  'Jaaaaaaah /herzi',
  'Klar Bernd, schließlich sollst du dich hier wohl fühlen /:3',
  'Ja, das macht du eh viel zu selten /erklär',
  'Klaro Bernd /2umarm',
  'Ja klar /kadse',
  'Das passt grade zum Thema, deshalb: Ja!',
  '/jf',
  'Das ist immer eine gute Idee',
  'Du hast meine uneingeschränkte Zustimmung',
  'Oui, Monsieur',
  'Ja und das ist gut so /top',
  'Das ist widerlich, moralisch höchst verwerflich und obendrein illegal. Ich stimme zu',
  'Weil du es bist /aww',
  'fraglos',

  // Hier irgendwas
  'Vielleicht',
  'Frage wurde im FAQ nicht gefunden.',
  'Bitte formulieren Sie die Frage neu.',
  'Bin grad am essen, frag später noch ein mal nach.',
  'Nur, wenn es dem Führer dient /führer',
  'Du musst etwas lauter sprechen',
  'Bei der nächsten Frage schlag ich dir in die Fresse, dass schwör ich. /kinski',
  'Ich gebe einem Menschen doch keine Auskunft /oho',
  'Gegenfrage : "Haben wir noch Pepps?"',
  'Nur wenn du in deinem Leben noch nie gefickt oder geküsst hast /tja',
  'Gut das du mich das fragst Bernd. Weiß ich auch nicht und jetzt verpiss dich /schelle ',
  'Kann grade nicht, hab Bierschiss /kabouter',
  'Frag Alkoholiker',
  'Fragen erfordern ab sofort eine KrautSync Platin Mitgliedschaft',
  'Ich bin nicht sicher, erstmal nen Schnaos /saufi',
  'Lauer Meer!',
  'Hab grade keine Zeit mir über deine Fragen Gedanken zu machen',
  'Für die Antwort: Like, Share und Subscribe! /chikkin',
  'Frag deine Mudda',
  'Deine Rechtschreibung ist eine Beleidigung. Ich weigere mich zu antworten. Heil Hitler.',
  'Wenn du meinst...',
  'Wenn ich dir das sage, muss ich leider deine Festplatte löschen.',
  'Du stellst die falschen Fragen.',
  'Bist du denn überhaupt bereit für die Antwort?',


  // Hier die negativen
  'Negativ',
  'Negertief',
  'Auf gar keinen Fall',
  'Abgelehnt',
  'Ich stimme nicht zu',
  'Schleich di!',
  'Piss dich Alde',
  'Bist du bescheuert?',
  'Ich halte das für keine gute Idee',
  '/nein',
  'Ich verbiete es!',
  'Ney',
  'Nein, und der Geist von Dr. Axel Stoll ist hierüber nicht begeistert.',
  'Nein, denn es dient nicht dem Führer /hitler',
  '/allesfalsch',
  'Den Fehler hat schon Lolibunny begangen',
  'Bist du denn total bekloppt?',
  'Höhöhö nö.',
  'Wat? Nein! Das widerspricht meinem germanischen Sittlichkeitsgefühl.',
  'Natürlich nicht, DU DUMME SAU! /kinski ',
  'Nö, wieso denn auch.',
  'Nein, und frag nicht wieder, du Versager.',
  'Besser nicht, die Juden wünschen das nicht.',
  'Ausgeschlossen. Allein der Grundgedanke der Frage bricht mindestens 10 Gesetze im Seerecht.',
  'Welchen Teil von "Nein" hast du nicht verstanden?',
  'Nyat. Du hast vergessen Daumen zu machen!',
  'Nö /2bescheuert',
  'Nein! Wie wärs wenn ich dir STATTDESSEN IN DIE FRESSE HAUE /kinski',
  'Dafür ist es noch zu früh! /maus',
  'Nein',
  'Nein, der Führer würde sich im Grabe umdrehen /mettweini',
  'Nein, dein dumme Fragen Kontingent für heute ist aufgebraucht',
  'Das kannst du jetzt echt nicht bringen /maus',
  'Ich glaube nein Bernd, tut mir leid /umarm',
  'Für positive Antworten ist eine KrautSynch Platin Mitgliedschaft erforderlich https://krautsynch.org/subscribe',
  'Mit der Kraft von 9000 Sonnen, NEIIIIN /ree',
  'Nee, das ist eklig Bernd!',
  'Hab Axel im Himmel befragt, er sagte Nein /allesfalsch',
  'Computer sagt nein',
  'Nein, Schnufti würde das nicht mögen /3kmett',
  'N zum E zum I zum N /snoop',
  'Ich habe es mehr als 10 mal durchgerechnet, aber es bleibt bei einem Nein /feelsbad',
  'Leider nein mein Süßer /knuddeln',
  'Nein, das ist seit Neuestem faboten /2maas',
  'Nein, das ist unter deinem Niveau',
  'Nee - Tu mal lieber die Möhrchen',
  'Nein, das macht mir Angst /angst',
  'Niemals /finger',
  'Du willst es doch selber nicht',
  'Auf keinen Fall',
  'Negativ',
  'NEIN!',
  'NIEMALS! /allesfalsch',
  'Keineswegs',
  'Unter keinen Umständen',
  `Ist sich mit ${randuser} darüber einig geworden: Nein. /finger`,
  `Den Fehler hat ${randuser} schon gemacht, Nein.`,
  'Ne, Hassel nicht den Hoff, Bernd /maus ',
  'Berndo tat den gleichen Fehler und dann fiel Lauerstein ihm in den Rücken',
  'HaHa... Nein /3nein',
  'Das verstößt mit Sicherheit gegen §86a StGB /schock',
  'Wegen Leuten wie dir haben wir jetzt das NetzDG!',
  'Nur über meine Leiche!',
  'Allein die Frage regt mich doch schon wieder auf! /mett',
  'abstrus',
  '/5nein'
]
