module.exports = [
  "Die Natur ist stärker als der Mensch. Deren Signale, die uns täglich präsentiert werden, sind Konsequenzen unserer  Sucht nach Macht und Habgier. Ungeachtet bleibt dabei jedoch, dass wir den Lebensraum unserer Kinder dadurch zerstören.",
  "Die Kraft, die man braucht, um aktiv zu werden, entsteht dadurch, dass man durchhält.",
  "Wer gelitten hat, sieht und begreift.",
  "In wandelnden Zeiten gibt es keinen Grund vor Angst zu erstarren, denn positive Zeiten kommen auf uns zu. Jeder von uns ist in der Lage, die Welt ein kleines Stück zu verbessern, dabei ist jedoch auch jeder einzelne in der Pflicht, seinen eigenen Beitrag zu leisten.",
  "Der bewusst gelebte Moment kann reicher sein als ein ganzer Tag",
  "Die klare Bewusstheit führt zu einer an den Realitäten orientierten Lebenshaltung und ist in vieler Hinsicht heilsam.",
  "Haben Sie schon mal versucht, eine Bilanz Ihres Lebens aufzustellen? Oder haben Sie schon beim Lesen des Wortes Bilanz gedacht, Buchhaltung ist nicht mein Ding - danke, kein Interesse?",
  "Wer aufhört dankbar zu sein, ist niemals dankbar gewesen.",
  "Die Leichtigkeit des Seins liegt nicht im Denken.",
  "Wer offen und aufrichtig durchs Leben schreitet, braucht sich vor der Ehrlichkeit nicht zu fürchten.",
  "Erst wenn wir aufhören so sein zu wollen wie andere, finden wir den Zugang zu persönlichem Erfolg und damit verbundenem Glück.",
  "Erkenntnis ist eine Form der Annäherung, d.h. der Bewegung, die vom Staunen ausgeht und auf die Sache zugeht.",
  "Go with the flow.",
  "Nur wer gibt was er kann, wird selbst bekommen was er braucht. Schenke Freude und Du wirst Freude erhalten.",
  "Ganzheitlich betrachtet sind Menschen Teile eines Gesamtwerkes. Sie verbinden Energie durch die Kraft ihrer Gedanken mit Materie und lassen sie so zu einer in sich geschlossenen Einheit werden.",
  "Zukunft gestalten bedarf einer Weise der Achtsamkeit. Sie kann nicht voraus gesagt werden, doch sie lässt sich bedenken und entwerfen.",
  "Geduld beruht auf der Gewissheit, dass alles was geschieht einen Sinn hat und gut, gewollt und richtig ist.",
  "Oft ist der Mensch darauf bedacht, die Zukunft zu planen und vergisst dabei, in der Gegenwart zu leben.",
  "Was heute richtig ist, kann morgen schon falsch sein. Und was heute falsch erscheint, kann morgen schon als richtig erachtet werden.",
  "Wer die Geduld verliert, verliert die Kraft und die Möglichkeit, die vergehende Zeit positiv zu gestalten.",
  "Die Wiederherstellung einer verlorenen Gesundheit ist wesentlich schwieriger als die Aufrechterhaltung eines gesunden Zustands.",
  "Durch den Glauben an sich selbst lassen sich Wünsche erfüllen.",
  "Glück existiert nur an einem einzigen Ort. In der Gegenwart.",
  "Alles hat seine Zeit, sagt man. Aber viel zu wenig gönnen wir es uns, oder können wir es uns leisten, Gedanken fließen zu lassen.",
  "Man kann nur handeln, indem man in der Zeit wirkt, indem man aus der Vergangenheit heraus in der Gegenwart die Zukunft gestaltet.",
  "Ein Heilmittel wirkt dann heilsam, wenn es mit Dir agieren kann - und Du mit ihm.",
  "Man findet Glück nicht indem man aufs Glück, sondern auf die Herausforderungen des Lebens schaut und sich ihnen stellt.",
  "Die Hoffnung ist lediglich eine Parallele zum Wollen und Machen.",
  "Alle können sich gegenseitig inspirieren und bereichern.",
  "Nutze den Augenblick, der sich dir nur einmal bietet.",
  "Menschen kämpfen gegen Gewalt, gegen Terrorismus, gegen Krebs, gegen Armut - eben gegen alles was sie nicht wollen. Es ist sinnvoller, für das zu kämpfen was man will.",
  "Einen Grund zum Klagen hat nur derjenige, der denkt, dass es niemanden gibt, dem es schlechter geht.",
  "Kommunizieren anstatt Beobachten, bedeutet Wissen anstatt Vermuten.",
  "Es ist nicht sinnvoll, nach einem Unglück den Rest des Lebens mit Selbstanklagen zu verbringen, die eigene Seele in Schuldgefühlen zu baden. Damit schwächt sich der schuldig Gewordene selbst, bringt sich nicht weiter und findet nicht die Kraft zu sinnvollen, zukunftsweisenden Aktionen.",
  "Der Kreis schließt sich nicht. Mut zur Lücke, dem Fluss des Lebens. Würde er sich schließen, würde er zur Stille werden. Finden wir Mut, dann fließt das Leben. Eine Lücke im Nichts, alles umfassend.",
  "Fit für eine Krise macht sich, wer gedanklich ständig in Bewegung bleibt und Wandel als eine Gegebenheit akzeptiert.",
  "Wer weiß, wofür er bereit wäre zu sterben, weiß demnach auch, wofür er leben sollte.",
  "Träume nicht Dein Leben, sondern lebe Deinen Traum.",
  "Die Erde ist keine Maschine, kein Mechanismus, kein langsam zu Ende tickender Motor, sondern lebendiger Lebensraum.",
  "Wenn man akzeptiert, dass alle Menschen unterschiedlich sind, bedeutet das auch, dass es legitim ist, eine unterschiedliche Auffassung von Anstand und Respekt zu haben. Entscheidend dabei ist nur, dass man sich selbst am nächsten Tag im Spiegel ins Gesicht schauen kann.",
  "Durch Aktivität lässt sich alles meistern.",
  "Wenn wir unsere Wahrnehmung verändern, eröffnen sich uns neue Möglichkeiten.",
  "Das Leben steckt voller Möglichkeiten und jeder Moment ist eine neue Chance.",
  "Zur Entscheidung bedarf es Mut.",
  "Etwas Neues zu beginnen bedarf genauso viel Mut, wie etwas Bestehendes zu beenden.",
  "Die Natur heilt alle Wunden.",
  "Neid ist lediglich ein Ausdruck der eigenen Angst, weniger geachtet zu werden als andere.",
  "Neues entsteht nicht durch Festhalten an Bestehendem.",
  "Wenn gute Gründe für eine Neuorientierung sprechen, sollte man seiner inneren Stimme folgen.",
  "Nichts, entsteht von alleine.",
  "Erfolg, den wir aus unserem Herzen heraus erreicht haben, schlägt jede bisherige Erfolgsquote. Und die Quote bestimmt jeder für sich selbst.",
  "Man kann die Realität nur zur Kenntniss nehmen oder ignorieren.",
  "Man sollte nicht darüber streiten, was richtig oder falsch ist, sondern man sollte erproben, was durchsetzbar ist, was am weitesten in die Zukunft weist und was akut das Wirksamste ist.",
  "Das Zentrum der Kraft bildet sich dort, wo Ruhe herrscht, wo einer stehen bleibt, ganz zentriert, ganz still, ganz ruhig, und das Wesentliche im Blick behält.",
  "Nicht die Schönheit entscheidet was wir lieben, sondern die Leidenschaft entscheidet was wir schön finden.",
  "Wunscherfüllung ist eine Willensschulung.",
  "Man glaubt was man sieht, aber man kann auch sehen was man man glaubt.",
  "Ich bin wie ich bin und ich bin toll.",
  "Was ist sinnvoller? Mehr Schein als Sein oder mehr Sein als Schein.",
  "Wenn es um Selbstbetrachtung geht, löst man sich aus sich selbst heraus. Man teilt sich in den Betrachter und den Betrachtenden.",
  "Entscheidungen sind Sinn stiftend, sei es vielleicht auch nur für eine vorübergehende Zeit.",
  "Der Sinn ergibt sich aus der Übereinstimmung mit dem, was man in seinem Leben aus sich machen wollte.",
  "Die wesentlichen Begegnungen im Leben sind die Momente der Stille.",
  "Wer sich im Zuhören übt, auf die Argumente anderer achtet, tolerant ist, Zivilcourage entwickelt und keine Scheu hat, anderen zu dienen, hat eine Chance darauf, dass seine Handlungen und Ideen Klarheit und Festigkeit erlangen.",
  "Das Wesentliche ist der innere Prozess, der durch äußere Umstände nur angestoßen, vielleicht durch einen Teil sogar gesucht und herbei inszeniert worden ist.",
  "Man verändert die Welt, indem man sich selbst verändert.",
  "Wenn Reden leichter als Tun und Versprechen leichter als Halten ist, sind Moral und Ethik weit entfernt.",
  "Ein gehaltenes Versprechen steigert nicht nur unser eigenes Selbstvertrauen, sondern auch das Vertrauen der anderen in uns.",
  "Zum Wagen gehört Risikobereitschaft, aber auch eine Kalkulierbarkeit des Risikos und eine realistische Einschätzung des eigenen Leistungsvermögens.",
  "Bei jedem Atemzug stehen wir vor der Wahl, das Leben zu umarmen oder auf das Glück zu warten.",
  "Man kommt der Wahrheit am nächsten, wenn man sich als Künstler und das eigene Leben als Kunstwerk versteht.",
  "Der werden, der man ist, heißt letztendlich: vollständig zu werden und sich ständig verändern.",
  "Wer wissen will, muss neugierig sein.",
  "Du kannst es nicht? Dann willst Du es nicht.",
  "Zeit ist limitiert. Ist es dann nicht besser, sich auf das Wesentliche zu konzentrieren.",
  "Man kann Zeitlosigkeit nicht diskutieren, wohl aber erfahren. Nämlich in Augenblicken in denen man in sich versunken ist und zwar so intensiv, dass man losgelöst ist von allem, auch vom Ticken der Uhr.",
  "Die Zukunft lässt sich nur positiv gestalten, wenn wir selbst bereits sind für Veränderungen.",
  "Es gibt keinen Grund in ungewissen Zeiten vor Angst zu erstarren, denn die Zukunft ist stets ungewiss. Positive Zeiten kommen auf uns zu  jedoch nur, wenn wir das auch wirklich wollen. Jeder von uns ist in der Lage, die eigene Zukunft positiv zu gestalten.",
  "Ob man das Leben lachend oder weinend verbringt, es ist dieselbe Zeitspanne.",
  "Man kann nur eine leere Schüssel füllen.",
  "Das Entscheidende ist das Tun, nicht so sehr die Ausführung.",
  "Wenn Du die Wahrheit erkennen willst, dann sei nicht für, aber auch nicht gegen etwas. Der Kampf zwischen dem \"Für etwas oder gegen etwas sein\" ist die schlimmste Krankheit der menschlichen Vernunft.",
  "Wenn du zurück zur Quelle willst, dann mußt du gegen den Strom schwimmen.",
  "Rühre an das Leere in deinem Leben, und dort werden Blumen blühen.",
  "Vor der Erleuchtung: Holz hacken und Wasser tragen. Nach der Erleuchtung. Holz hacken und Wasser tragen.",
  "Das Wasser, das zu rein ist, hat keine Fische.",
  "Still sitzen - Nichts tun - Der Frühling kommt - Das Gras wächst",
  "Bevor jemand Zen studiert, sind Berge Berge und Wasser ist Wasser; nach einem ersten Blick in die Wahrheit des Zen sind Berge nicht mehr Berge, und Wasser ist nicht länger Wasser; nach der Erleuchtung sind Berge wieder Berge, und Wasser ist wieder Wasser.",
  "Der Schüler ging zum Meister und fragte ihn: \"Wie kann ich mich von dem, was mich an die Vergangenheit heftet, lösen?\" Da stand der Meister auf, ging zu einem Baumstumpf und umklammerte ihn und jammerte: \"Was kann ich tun, damit dieser Baum mich losläßt?\"",
  "Alles was blüht, vergeht.",
  "Wirf deine Gedanken wie Herbstblätter in einen blauen Fluß, schau zu, wie sie hineinfallen und davontreiben  und dann: vergiß sie.",
  "Lächle anderen zu - und du lächelst deinem eigenen Herzen zu. Denn sie sind wie du.",
  "Klopf an den Himmel und dann hör auf den Klang.",
  "Zen hat das Ziel, die Aufmerksamkeit auf die Wirklichkeit selbst zu sammeln und nicht auf unsere intellektuellen oder emotionalen Reaktionen auf die Wirklichkeit. Und Wirklichkeit ist das stets Wachsende und sich Wandelnde und nicht zu Definierende, das wir Leben nennen und das nie auch nur einen Augenblick stehen bleibt, damit wir es in ein System von Kategorien und Ideen zwängen können.",
  "Den Schmetterling des Zen im Netz des Verstandes zu fangen - machen wir uns das klar, daß das nicht geht.",
  "Zen behauptet, Buddhismus zu sein, doch alle in den Sutras und Shastras dargelegten buddhistischen Lehren werden vom Zen als bloßes Papier betrachtet, das lediglich dazu taugt, den Schmutz des Intellekts wegzuwischen.",
  "Während des Aufenthalts in einem Tempel wurde Meister Tan-hsia kalt, also nahm er eine Holzstatue des Buddha vom Altar und warf sie ins Feuer. Der Hüter des Tempels war entsetzt und verärgert. Daraufhin stocherte der Meister in der Asche: \"Was macht Ihr da?\" wollte der Tempelhüter wissen. \"Ich suche nach heiligen Überresten\", erwiderte der Meister. \"Die findet Ihr doch sicher nicht in der Asche einer Holzstatue\", sagte der Hüter. \"Wenn das so ist\", meinte Tan-hsia, \"hättet Ihr dann noch ein paar Buddhas, damit ich mich wärmen kann?\"",
  "Meister Ikkyu riet, vor dem Studium buddhistischer Texte und endlosem Rezitieren der Sutras sollte ein Zen-Schüler die Liebesbriefe lesen lernen, die Schnee, Wind und Regen ihm schicken.",
  "Wenn ein Problem gelöst werden kann, warum unglücklich sein? Und wenn es nicht gelöst werden kann, was macht es dann für einen Sinn, unglücklich zu sein?",
  "Sei mindestens genauso ideen- und erfindungsreich in deiner Suche nach innerem Frieden, wie du es auch in der Welt des Wettkampfs und der Neurosen bist.",
  "Die Blume kehrt wieder zur Wurzel zurück.",
  "Wenn du es nicht von dir selbst bekommst, woher dann wohl?",
  "Schüler: \"Gibt es etwas Staunenswerteres als die Natur?\" Meister: \"Ja, deinen Sinn für diese Wunder.\"",
  "Schüler: \"All diese Naturwunder ... die Bäume, die Berge, die Erde...., woher kommen sie?\" Meister: \"Woher kommt deine Frage?\"",
  "Schüler: \"Wie kann ich mein Selbst-Wesen wahrnehmen?\" Meister: \"Dein Selbst-Wesen ist das, was wahrnimmt. Ohne es gibt es keine Wahrnehmung.\"",
  "Schüler: \"Was ist der Pfad zur Befreiung?\". Seng-ts'an: \"Wer bindet dich?\" Schüler: \"Niemand bindet mich.\" Seng-ts'an: \"Weshalb möchtest du dann befreit werden?\"",
  "Sehr befremdet wollte Kaiser Wu von Bodhidharma wissen: \"Was ist die heilige Wahrheit des Buddhismus?\" Der erwiderte: \"Grenzenlose Leere - und nichts Heiliges darin. \"Verwirrt und allmählich ärgerlich werdend fragte Kaiser Wu: \"Wenn Ihr sagt, alles sei nichts, wer seid dann Ihr?\" Bodhidharma erwiderte: \"Ich weiß es nicht.\" Dazu fiel dem Kaiser nichts mehr ein, und Bodhidharma, der einsah, daß hier niemand seine Lehre verstehen würde, zog sich zurück und meditierte neun Jahre lang der Wand gegenüber.",
  "Zeig mir dein Urangesicht vor der Geburt deiner Eltern.",
  "Ein Schüler kam auf der Suche nach der Wahrheit des Buddhismus ins Kloster: \"Was willst du in einem Kloster?\" fragte der Meister. \"Warum kümmerst du dich nicht um den Schatz in deinem eigenen Hause?\"",
  "\"Was ist mein Schatz?\" fragte der Schüler. \"Der da fragt ist dein Schatz\", sagte der Meister.",
  "Vimalkirti befragte Manjushri über die von Buddha gelehrte Nicht-Zweiheit. Manjushri sagte: \"Diese Lehre ist realisiert von einem, der über die Formen hinausblickt und ohne Beweisführung versteht. So sehe ich es, und du?\" Zur Antwort auf diese Frage schloß Vimalkirti den Mund und schwieg.",
  "Du kannst den Pfad nicht beschreiten, solange du nicht selbst der Pfad geworden bist.",
  "Einst wollte ein Meister gerade zu einer Darlegung anheben, als ein Vogel zu singen begann. Der Meister sagte nichts, und alle lauschten dem Vogel. Als dieser verstummte, sagte der Meister, die Darlegung sei bereits erfolgt  und ging seiner Wege.",
  "Für alle Wesen will ich unbegrenzte Liebe, Mitgefühl, Mitfreude und Gleichmut entfalten, im Wissen um das Streben aller Lebewesen nach Glück.",
  "Sei gegenwärtig in allem, was du tust, die einzige Wirklichkeit ist jetzt. Solange du Vergangenem nachhängst oder Zukünftigem nachstellst, bist du nicht wirklich hier, am Leben.",
  "Bei einem Begräbnis klopfte ein Mönch an den Sarg und fragte: \"Tot oder lebendig?\" Der Meister erwiderte: \"Ich sage nicht lebendig, ich sage nicht tot.\"",
  "Hast du eine Meinung über die buddhistische Lehre, wird sie ein weltliches Ding. Hast du keine Meinung über weltliche Dinge, werden sie buddhistische Lehre.",
  "O reines und glänzendes Strahlen! O nachtvertreibende Sonne der Weisheit! O Siegerin über Sturm und Flammen! Deine Glorie füllt die Welt!",
  "Meister Hogen sagte zu einem Mönch: \"Sieh dir diesen Felsbrocken an. Ist er in deinem Geist oder außerhalb?\" Der Mönch antwortete: \"Nach der buddhistischen Lehre ist alles Projektion des Geistes, also nehme ich an, daß er in meinem Geiste ist.\" Hogen sagte: \"Ist es nicht beschwerlich, solch einen schweren Stein mit dir herumzuschleppen?\"",
  "Schüler: \"Ich habe nichts.\" Meister: \"Dann wirf es weg.\"",
  "Ist dein Blick auch nur leicht getrübt, siehst du nichts als Wahngebilde.",
  "Wenn einer eine Lüge erzählt, geben tausend andere sie als Wahrheit wieder.",
  "Ein Schüler, der die Leere des Geistes erlangt zu haben meinte, rühmte sich vor dem Meister: \"Jetzt weiß ich nichts mehr.\" Der Meister erwiderte: \"Wozu ächzend unter der Last dieses \"nichts mehr\" herumstolpern?\"",
  "Zuigan begrüßte sich selbst jeden Morgen und forderte sich auf: \"Bitte, wach' heute auf.\" Darauf antwortete er: \"Ja, das werde ich.\"",
  "Mein Mitgefühl für alle Lebewesen soll wie der grenzenlose Himmel sein. Befreit, muß der Geist nicht mehr an weltlichen Dingen festhalten. Wenn ich auch in dieser Welt der Illusion lebe, soll meine Meditation doch wie die Lotosblüte sein, die sich schön und makellos aus dem Schlamm erhebt. Mit geläutertem Geist huldige ich dem Buddha, dem Erleuchteten.",
  "Als Meister Takuan sich seinem Tode näherte, baten ihn seine Schüler, ein Gedicht zu hinterlassen. Er nahm einen Pinsel und schrieb ein einziges Wort: Traum.",
  "Wenn dein Geist stets gänzlich leer ist, wirst du die Reinheit erlangen. Doch denke nicht an sie, sonst verlierst du sie. Verfällst du jedoch wieder der Nicht-Reinheit, so beachte sie einfach nicht, und du wirst wieder frei sein.",
  "Wenn die Bergblumen erblühen, offenbart ihr Duft den wahren Sinn.",
  "Wenn der Bogen zerbrochen ist und du keine Pfeile mehr hast, dann schieß, schieß mit deinem ganzen Sein.",
  "Nichts ist so nah wie die Lehre von der »Soheit«. In einem Sandkorn habt ihr alles Land und alle Meere. Wenn wir die Wahrheit gefunden haben, dann gibt es auf der Großen Erde keinen einzigen Menschen mehr.",
  "Was ist die größte Weisheit? Das tägliche Leben.",
  "Die Summe der Leiden in der Welt bleibt immer konstant.",
  "Das Bewußtsein des Nichtwissens ist der Anfang des Zweifels, der zur Weisheit führt",
  "Wenn du etwas tust, dann tu es so gut wie möglich. Achte nicht auf das Ergebnis, das Ergebnis ist nicht wichtig.",
  "Nicht deswegen ist der Mensch den übrigen Wesen überlegen, weil er sie unbarmherzig martert, sondern deshalb, weil er gegen alle Lebewesen mitleidig ist.",
  "Das Leben ist niemals nur Armut.",
  "Wer seinen eigenen Weg geht, dem wachsen Flügel.",
  "Das Leben ist einmalig. Der Tod ist endgültig.",
  "Der Lehrer ist da, wenn der Schüler dafür bereit ist.",
  "Das Unglück ist es, worauf das Glück beruht. Das Glück ist es, was das Unglück birgt. Wer kennt das Ende?",
  "Tu es oder tu es nicht, aber höre auf, es zu versuchen.",
  "Wenn die Achtsamkeit etwas Schönes berührt, offenbart sie dessen Schönheit. Wenn sie etwas Schmerzvolles berührt, wandelt sie es um und heilt es.",
  "Der Kampf in unserem Bewußtsein, zwischen richtig und falsch, führt zur Krankheit des Geistes.    ",
  "Wasser erstarrt zu Eis, Eis schmilzt zu Wasser. Was geboren ist, stirbt wieder; was gestorben ist, lebt wieder. Wasser und Eis sind letztlich eins. Leben und Tod, beides ist gut so.",
  "Der Regen hat aufgehört, die Wolken haben sich verzogen, das Wetter ist wieder klar. Wenn dein Herz geläutert ist, sind alle Dinge in deiner Welt geläutert. Lass diese flüchtige Welt sein, lass dich Selbst sein. Dann werden dich der Mond und die Blumen auf dem großen Weg begleiten.",
  "Hier ist das ungekünstelte Ich, dein Urangesicht. Hier ist die Landschaft deiner Geburt, unverhüllt und schön.",
  "Höre auf, daran zu denken und darüber zu sprechen, und es gibt nichts, was du darüber nicht wissen kannst.",
  "Die Blume sehen heisst, zur Blume werden, die Blume sein, als Blume blühen und sich an Sonne und Regen erfreuen.",
  "Mach dich frei von deinem Halt.",
  "Ich wurde allein geboren. Ich werde allein sterben. Und dazwischen bin ich Tag und Nacht allein.",
  "Erkennst du denn nicht, dass du nur keine Vorstellungen und keine Angst haben mußt, um den Buddha direkt vor dir zu sehen? ",
  "Hier ist es, eben jetzt. Denk darüber nach und du verfehlst es.",
  "Das Leben ist so. Der Tod ist so. Vers oder nicht Vers, wozu so viel Aufhebens?",
  "In gewissem Sinne ist Zen, das Leben zu fühlen und nicht, Gefühle in Bezug auf das Leben zu haben.",
  "Was schenken sich Zen-Buddhisten zum Geburtstag? Nichts!",
  "Du kannst nicht den Geist benutzen, um den Geist zu suchen, nicht Buddha benutzen, um Buddha zu suchen, nicht den Dharma benutzen, um den Dharma zu suchen.",
  "Der Schüler fragte den Meister: \"Was ist der tiefste Sinn des Buddhismus?\" Der Meister verneigte sich tief vor seinem Schüler.",
  "Ihr Narren! Worauf seid ihr so emsig aus? Weshalb versucht ihr einen Kopf auf euren Kopf zu setzen? Euer Kopf ist doch schon da, wo er sein muß.",
  "Schüler: \"Wie finde ich mein Buddha-Wesen?\" Meister: \"Du hast kein Buddha-Wesen.\" Schüler: \"Wie ist es mit den Tieren?\" Meister: \"Die haben Buddha-Wesen.\" Schüler: \"Warum habe ich dann keines?\" Meister: \"Weil du fragen musst.\"",
  "Das Leben ist eine Tatsache und Erklärungen sind hier weder notwendig noch angebracht.",
  "Schüler: \"Was ist Zen?\" Meister: \"Es ist direkt vor deinen Augen.\" Schüler: \"Weshalb sehe ich es dann nicht?\" Meister: \"Weil du ein Ich hast.\" Schüler: \"Wenn ich die Ich-Vorstellung nicht mehr habe, werde ich dann das Zen verwirklichen?\" Meister: \"Wo kein Ich ist, wer will da Zen verwirklichen\"",
  "Wenn du liebst, verbrenne dich ganz, wie in einem Freudenfeuer, keine Spur soll von dir bleiben.",
  "Hast du eine Meinung über die buddhistische Lehre, wird sie ein weltliches Ding. Hast du keine Meinung über weltliche Dinge, werden sie buddhistische Lehre.",
  "Um den Geist zu erkennen, trachte zuerst, den Ursprung deines Denkens zu finden. Schlafend oder arbeitend, stehen oder sitzend, frage dich ernsthaft: \"Was ist mein Geist?\"",
  "Wenn du den Himmel, die Erde und alle Lebewesen verstehen möchtest, dann beginne mit einem Reiskorn.",
  "Keine Schneeflocke fällt je auf die falsche Stelle.",
  "Zen wird Zen, wenn du du selbst wirst.",
  "Gib das Ich auf, und die Welt wird ich.",
  "Du willst Gutes tun? Dann tue es! Achte dabei nicht auf Anerkennung, auf Belohnung und auf Dank. Wenn du Gutes tust, dann tue es wegen seiner selbst, und du wirst Anerkennung, Belohnung und Dank empfangen, ohne es zu ahnen.",
  "Das Wollen des Einzelnen hat selten Erfolg, wenn es sich gegen die Menge stellt. Den Willen der Menge anzugreifen hat noch weniger Aussicht auf Erfolg. Und dennoch vermag der Wille der Menge das Wollen des Einzelnen nicht zu brechen.",
  "Eine Verbeugung, die nicht aus dem Herzen kommt, hat nicht mit Höflichkeit zu tun. Eine Verbeugung, die Ausdruck tiefen Wünschens ist, bringt dir wahre Achtung ein.",
  "Wer den Ruhm nicht verdient, kämpft um ihn. Wer ihn verdient, den trifft er im Schlaf.",
  "Willkür verursacht Schaden, Beliebigkeit verursacht Not.",
  "Vorzugeben, etwas zu wissen, von dem man nichts weiß, zeugt nicht von Klugheit. Vorzugeben, dass sich etwas ereignet, obwohl sich nichts ereignet, zeugt nicht von Erfüllung. Vorzugeben, etwas zu verwirklichen, das man nicht verwirklichen kann, zeugt nicht von Geisteskraft. Wähle deshalb, was du nicht tun willst.",
  "Wann immer du der erste werden möchtest, wird es einen geben, der dich verdrängen will. Was immer du zuerst erreichen möchtest, wird stets von einem anderen erlangt. Da dies ein Gesetz der Erde ist, bleibe zurückhaltend, und du wirst ans Ziel gelangen - ohne es zu merken.",
  "Rechtschaffenheit und Klarheit sind das beste für das Herz, Aufrichtigkeit und Freimut das beste für das Ansehen. Wahrhaftigkeit und Ehrfurcht sind das beste für das Sprechen, Folgerichtigkeit und Ordnung das beste für das Leben.",
  "Wer in seinen Worten maßlos ist, wird sie schwerlich in die Tat umsetzen können.",
  "Wer sich selbst nicht schätzt, verdient es, nicht geschätzt zu werden. Wer anderes nicht schätzt, verdient es nicht, geschätzt zu werden.",
  "Wenn du lernst, einen Schritt zurückzugehen, machst du einen Schritt vorwärts: Denn selbst wenn du großen Reichtum dein eigen nennst, hilft er dir nicht, dich glücklicher zu fühlen, solange du nicht fähig bist, ihn für Gutes einzusetzen.",
  "Zu viel an Reichtum ist die Quelle der Beschwerden. Zu viel an Fertigkeit der Ursprung allen Elends. Zu viel an Ruhm ist die Quelle der Verleumdung. Zu viel an Freude der Ursprung aller Trauer.",
  "Meide nicht die guten Taten, nur weil sie nicht beachtet werden. Doch meide die schlechten Taten, auch wenn sie nicht beachtet werden",
  "Es ist leichter, gemeinsam in Notzeiten zu leben, als bei guten Zeiten zusammenzuhalten.",
  "Was hast du bei einer Frage zu verlieren? Das \"Nein\" hast du, das \"Ja\" kannst du gewinnen.",
  "Der Rechtschaffene ist zurückhaltend in seinen Worten, aber unübertrefflich in seinen Taten.",
  "Indem man über andere schlecht redet, macht man sich selbst nicht besser.",
  "In allen Dingen hängt der Erfolg von den Vorbereitungen ab.",
  "Wer hoch hinaus will, muss unten anfangen.",
  "Guter Rat schmeichelt vielfach nicht dem Ohr Gerade jener Ratschlag, der uns widerstrebt, kann wertvoll sein",
  "Konzentration und Geduld weisen den Weg.",
  "Es gibt Fähigkeiten, die man erlernen kann. Es gibt Fähigkeiten, die man schon in sich trägt. Die einen sind nicht besser als die anderen. Entscheidend ist, wofür man sie einsetzt.",
  "Nichts suchen heißt gelassen bleiben.",
  "Wenn die Achtsamkeit etwas Schönes berührt, offenbart sie dessen Schönheit. Wenn sie etwas Schmerzvolles berührt, wandelt sie es um und heilt es.",
  "Lass alles los! Lass auch das Loslassen los!",
  "Tritt er in den Wald so bewegt sich kein einziges Gras taucht er in das Wasser ein so bildet sich nicht eine einzige Welle niemand bemerkt ihn weil er von sich selbst keine Notiz nimmt.",
  "Befreie dich von deinem Selbst und handle aus deinem Selbst!"
]
